package me.m0dii.modules.automation;

public enum AutomationEventType {
    TICK_INTERVAL,
    PLAYER_MOVE,
    WORLD_JOIN,
    WORLD_LEAVE,
    DIMENSION_CHANGE,
    CHAT_RECEIVED_REGEX,
    SCREEN_CHANGED,
    WEATHER_CHANGED,
    HOTBAR_SLOT_CHANGED,
    HELD_ITEM_CHANGED,
    PLAYER_LEVEL_CHANGED,
    PLAYER_HEALTH_CHANGED,
    PLAYER_FOOD_CHANGED,
    PLAYER_DEATH
}
